apiVersion: v2
name: infegate
description: Infegate auditable AI gateway and management interface
type: application
kubeVersion: ">=1.30.0-0"
version: 2.4.0
appVersion: "1.1.0"
home: https://infegate.com
sources:
  - https://github.com/demirtechcom/infegate
maintainers:
  - name: DemirTech
    url: https://demirtech.com
annotations:
  licenses: Apache-2.0 AND OFL-1.1
